name: update

on:
    push:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: "recursive"

            - uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: Install NPM Packages
              run: npm install

            - name: Build Documentation
              run: npm run build

            - name: Copy CNAME
              run: cp ./CNAME ./_book

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages # The branch the action should deploy to.
                  FOLDER: _book # The folder the action should deploy.
